export enum Exchange {
  CURVE = "CURVE",
  ONE_INCH_V5 = "ONE_INCH_V5",
  PARASWAP = "PARASWAP",
  PMM_2 = "PMM_2",
  PMM_2_KYC = "PMM_2_KYC",
  UNISWAP_V2 = "UNISWAP_V2",
  UNISWAP_V3 = "UNISWAP_V3",
}
