export enum PriceFeedType {
  NONE = "NONE",
  NATIVE_TOKEN = "NATIVE_TOKEN",
  PRIMITIVE_CHAINLINK = "PRIMITIVE_CHAINLINK",
  PRIMITIVE_REDSTONE = "PRIMITIVE_REDSTONE",
  DERIVATIVE_ARRAKIS_V2 = "DERIVATIVE_ARRAKIS_V2",
  DERIVATIVE_BALANCER_V2_GAUGE_TOKEN = "DERIVATIVE_BALANCER_V2_GAUGE_TOKEN",
  DERIVATIVE_BALANCER_V2_STABLE_POOL = "DERIVATIVE_BALANCER_V2_STABLE_POOL",
  DERIVATIVE_BALANCER_V2_WEIGHTED_POOL = "DERIVATIVE_BALANCER_V2_WEIGHTED_POOL",
  DERIVATIVE_COMPOUND = "DERIVATIVE_COMPOUND",
  DERIVATIVE_CURVE = "DERIVATIVE_CURVE",
  DERIVATIVE_ERC4626 = "DERIVATIVE_ERC4626",
  DERIVATIVE_ETHERFI = "DERIVATIVE_ETHERFI",
  DERIVATIVE_PEGGED_DERIVATIVES = "DERIVATIVE_PEGGED_DERIVATIVES",
  DERIVATIVE_REVERTING = "DERIVATIVE_REVERTING",
  DERIVATIVE_UNISWAP_V2_POOL = "DERIVATIVE_UNISWAP_V2_POOL",
  DERIVATIVE_WSTETH = "DERIVATIVE_WSTETH",
  DERIVATIVE_YEARN_VAULT_V2 = "DERIVATIVE_YEARN_VAULT_V2",
}

export const primitivePriceFeeds = [PriceFeedType.PRIMITIVE_CHAINLINK, PriceFeedType.PRIMITIVE_REDSTONE];

export const derivativePriceFeeds = [
  PriceFeedType.DERIVATIVE_ARRAKIS_V2,
  PriceFeedType.DERIVATIVE_BALANCER_V2_GAUGE_TOKEN,
  PriceFeedType.DERIVATIVE_BALANCER_V2_STABLE_POOL,
  PriceFeedType.DERIVATIVE_BALANCER_V2_WEIGHTED_POOL,
  PriceFeedType.DERIVATIVE_COMPOUND,
  PriceFeedType.DERIVATIVE_CURVE,
  PriceFeedType.DERIVATIVE_ERC4626,
  PriceFeedType.DERIVATIVE_ETHERFI,
  PriceFeedType.DERIVATIVE_PEGGED_DERIVATIVES,
  PriceFeedType.DERIVATIVE_REVERTING,
  PriceFeedType.DERIVATIVE_UNISWAP_V2_POOL,
  PriceFeedType.DERIVATIVE_WSTETH,
  PriceFeedType.DERIVATIVE_YEARN_VAULT_V2,
];
