export {
  Action,
  callEncode,
  callDecode,
  type CallArgs,
  createEncode,
  createDecode,
  type CreateArgs,
  removeEncode,
  removeDecode,
  type RemoveArgs,
  reactivateEncode,
  reactivateDecode,
  type ReactivateArgs,
} from "../_internal/ExternalPositionManager.js";
