name: Verify Environment
on:
  workflow_call:

permissions: {}

jobs:
  verify_environment:
    name: Test ${{ matrix.app }} ${{ matrix.release }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        release: [arbitrum.sulu, base.sulu, ethereum.sulu, polygon.sulu]

    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run tests
        run: pnpm vitest --project @enzymefinance/environment
        env:
          VITE_ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          VITE_RELEASE: ${{ matrix.release }}
          VITE_COINGECKO_MINUTE_RATE: 5 # low max rate (per app per shard)
