name: Verify
on:
  workflow_call:

permissions: {}

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Check linting
        run: pnpm lint

  types:
    name: Types
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run build
        run: pnpm build
      - name: Check types
        run: pnpm typecheck

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run build
        run: pnpm build

  test:
    name: Test (${{ matrix.shard }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run tests
        working-directory: packages/sdk
        run: pnpm vitest --shard ${{ matrix.shard }}
        env:
          VITE_ANVIL_FORK_URL: ${{ secrets.VITE_ANVIL_FORK_URL }}
          VITE_ANVIL_FORK_BLOCK_NUMBER: ${{ secrets.VITE_ANVIL_FORK_BLOCK_NUMBER }}
          VITE_ANVIL_FORK_URL_POLYGON: ${{ secrets.VITE_ANVIL_FORK_URL_POLYGON }}
          VITE_ANVIL_FORK_BLOCK_NUMBER_POLYGON: ${{ secrets.VITE_ANVIL_FORK_BLOCK_NUMBER_POLYGON }}
