name: Verify Environment Assets

on:
  pull_request:
    branches: [main] # Adjust branches as needed

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      ethereum: ${{ steps.filter.outputs.ethereum }}
      polygon: ${{ steps.filter.outputs.polygon }}
      arbitrum: ${{ steps.filter.outputs.arbitrum }}
      base: ${{ steps.filter.outputs.base }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ethereum:
              - 'packages/environment/src/assets/ethereum.ts'
            polygon:
              - 'packages/environment/src/assets/polygon.ts'
            arbitrum:
              - 'packages/environment/src/assets/arbitrum.ts'
            base:
              - 'packages/environment/src/assets/base.ts'

  verify_environment:
    name: Test ${{ matrix.release }}
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.ethereum == 'true' || needs.changes.outputs.polygon == 'true' || needs.changes.outputs.arbitrum == 'true' || needs.changes.outputs.base == 'true'
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        release: [arbitrum.sulu, base.sulu, ethereum.sulu, polygon.sulu]

    steps:
      - name: Log changed files
        run: echo "Hello"
      # - name: Clone repository
      #   uses: actions/checkout@v4
      # - name: Install dependencies
      #   uses: ./.github/actions/install-dependencies
      # - name: Run tests
      #   run: pnpm vitest --project @enzymefinance/environment
      #   env:
      #     VITE_ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      #     VITE_RELEASE: ${{ matrix.release }}
      #     VITE_COINGECKO_MINUTE_RATE: 5
